server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles:
    active: dev   #环境设置: dev、test、prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  jackson:
    time-zone:  GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #控制台打印完整带参数SQL语句




