server:
  port: 8009
spring:
  application:
    name: service-acl
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  jackson:
    time-zone:  GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        #nacos注册中心服务地址
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.2.107
    port: 6379
    database: 0
    timeout: 1800s
    lettuce: #SpringBoot2.0默认采用Lettuce客户端来连接Redis服务端
      pool: #redis连接池
        #最大活跃链接数 默认8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 最大空闲连接数 默认8
        max-idle: 5
        # 最小空闲连接数 默认0
        min-idle: 0

mybatis-plus:
  mapper-locations:
  - classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #控制台打印完整带参数SQL语句

